name: Build Electron App

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Generate macOS Icon
        if: runner.os == 'macOS'
        shell: bash
        run: |
          rm -rf build/icons/mac
          mkdir -p build/icons/mac

          mkdir -p /tmp/S3Hub.iconset

          sips -z 16 16 build/icon.png --out /tmp/S3Hub.iconset/icon_16x16.png
          sips -z 32 32 build/icon.png --out /tmp/S3Hub.iconset/icon_16x16@2x.png

          sips -z 32 32 build/icon.png --out /tmp/S3Hub.iconset/icon_32x32.png
          sips -z 64 64 build/icon.png --out /tmp/S3Hub.iconset/icon_32x32@2x.png

          sips -z 128 128 build/icon.png --out /tmp/S3Hub.iconset/icon_128x128.png
          sips -z 256 256 build/icon.png --out /tmp/S3Hub.iconset/icon_128x128@2x.png

          sips -z 256 256 build/icon.png --out /tmp/S3Hub.iconset/icon_256x256.png
          sips -z 512 512 build/icon.png --out /tmp/S3Hub.iconset/icon_256x256@2x.png

          sips -z 512 512 build/icon.png --out /tmp/S3Hub.iconset/icon_512x512.png
          sips -z 1024 1024 build/icon.png --out /tmp/S3Hub.iconset/icon_512x512@2x.png

          iconutil -c icns \
            /tmp/S3Hub.iconset \
            -o build/icons/mac/icon.icns

          file build/icons/mac/icon.icns

      - name: Build App
        run: npm run build && npx electron-builder --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_ENC_KEY: ${{ secrets.VITE_ENC_KEY }}